# Generated by Django 3.1.5 on 2022-10-06 11:08

import datetime
from django.db import migrations, models
import misc.common_classes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=8)),
            ],
            bases=(models.Model, misc.common_classes.Initable),
        ),
        migrations.CreateModel(
            name='GoodsEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_id', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('ship_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ship_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='HotEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=32)),
            ],
            bases=(models.Model, misc.common_classes.Initable),
        ),
        migrations.CreateModel(
            name='KilledGoodsEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_id', models.CharField(blank=True, default='', max_length=32)),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=15)),
                ('ship_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ship_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='KilledMoneyEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_id', models.CharField(blank=True, default='', max_length=32)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('kill_date', models.DateTimeField(default='1970-01-01')),
                ('has_goods_entries', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='MoneyEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('human_id', models.CharField(blank=True, default='', max_length=32)),
                ('money', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=256)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('has_goodslines', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
            ],
            bases=(models.Model, misc.common_classes.Initable),
        ),
    ]
