# Generated by Django 3.1.5 on 2022-10-06 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('primepage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_group', to='primepage.partnergroup'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='cred_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_cr', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='deb_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_dr', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_employee', to='primepage.partner'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='hot_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_hot_entry', to='primepage.hotentry'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='parent_money_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_parent_entry', to='primepage.moneyentry'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_partner', to='primepage.partner'),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='cred_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_cr', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='deb_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_dr', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_employee', to='primepage.partner'),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='hot_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_hot_entry', to='primepage.hotentry'),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='killed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_killed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='parent_money_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_parent_entry', to='primepage.killedmoneyentry'),
        ),
        migrations.AddField(
            model_name='killedmoneyentry',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_money_entry_partner', to='primepage.partner'),
        ),
        migrations.AddField(
            model_name='killedgoodsentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goods_entry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='killedgoodsentry',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goods_entry_material', to='primepage.material'),
        ),
        migrations.AddField(
            model_name='killedgoodsentry',
            name='parent_money_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='killed_goods_entry_parent_entry', to='primepage.killedmoneyentry'),
        ),
        migrations.AddField(
            model_name='goodsentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_entry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsentry',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_entry_material', to='primepage.material'),
        ),
        migrations.AddField(
            model_name='goodsentry',
            name='parent_money_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_entry_parent_entry', to='primepage.moneyentry'),
        ),
    ]
