# Generated by Django 3.1.5 on 2022-10-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0003_auto_20221015_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
