# Generated by Django 3.1.5 on 2022-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0004_partner_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
