# Generated by Django 3.1.5 on 2022-10-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0005_auto_20221017_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyentry',
            name='has_goodslines',
        ),
    ]
