# Generated by Django 3.1.5 on 2022-10-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0006_remove_moneyentry_has_goodslines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50, verbose_name=''),
        ),
    ]
