# Generated by Django 3.1.5 on 2022-10-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0007_auto_20221028_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_group', to='primepage.partnergroup', verbose_name=''),
        ),
    ]
