# Generated by Django 3.1.5 on 2022-11-05 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepage', '0009_auto_20221029_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
