# Generated by Django 3.1.5 on 2022-11-06 22:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepage', '0010_auto_20221105_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
