# Generated by Django 3.1.5 on 2022-11-10 22:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepage', '0011_auto_20221106_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentry',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_created_by', to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='cred_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_cr', to='primepage.account', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='date',
            field=models.DateField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='deb_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_dr', to='primepage.account', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_employee', to='primepage.partner', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='hot_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_hot_entry', to='primepage.hotentry', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='humanid',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='parent_money_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_parent_entry', to='primepage.moneyentry', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='partner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_entry_partner', to='primepage.partner', verbose_name=''),
        ),
    ]
