# Generated by Django 3.1.5 on 2022-11-11 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0012_auto_20221110_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_group', to='primepage.partnergroup'),
        ),
    ]
