# Generated by Django 3.1.5 on 2022-11-12 13:42

from django.db import migrations, models
import django.db.models.deletion
import misc.common_classes


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0015_auto_20221112_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyentriesbunch',
            name='cred_account',
        ),
        migrations.RemoveField(
            model_name='moneyentriesbunch',
            name='deb_accounts',
        ),
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='parent_money_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_parent_entry', to='primepage.moneyentry'),
        ),
        migrations.CreateModel(
            name='AccPair',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_acc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_accpair_cr_acc', to='primepage.account')),
                ('dr_acc', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_accpair_dr_acc', to='primepage.account')),
            ],
            bases=(models.Model, misc.common_classes.Initable, misc.common_classes.ClassNameGetter),
        ),
        migrations.AddField(
            model_name='moneyentriesbunch',
            name='acc_pairs',
            field=models.ManyToManyField(related_name='primepage_moneyentriesbunch_acc_pairs', to='primepage.AccPair'),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='acc_pair',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_acc_pair', to='primepage.accpair'),
        ),
    ]
