# Generated by Django 3.1.5 on 2022-11-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0016_auto_20221112_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyentry',
            name='acc_pair',
        ),
    ]
