# Generated by Django 3.1.5 on 2022-11-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0019_auto_20221112_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotentry',
            name='cr_acc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_cr', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='hotentry',
            name='dr_acc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_dr', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='cr_acc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_cr', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='dr_acc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_dr', to='primepage.account'),
        ),
    ]
