# Generated by Django 3.1.5 on 2022-11-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0021_auto_20221114_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotentry',
            name='cr_acc1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_cr1', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='hotentry',
            name='cr_acc2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_cr2', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='hotentry',
            name='dr_acc1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_dr1', to='primepage.account'),
        ),
        migrations.AddField(
            model_name='hotentry',
            name='dr_acc2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_dr2', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='hotentry',
            name='cr_acc0',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_cr0', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='hotentry',
            name='dr_acc0',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_dr0', to='primepage.account'),
        ),
    ]
