# Generated by Django 3.1.5 on 2022-11-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0022_auto_20221114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_entry_partner', to='primepage.partner'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='partner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_entry_partner', to='primepage.partner'),
        ),
    ]
