# Generated by Django 3.1.5 on 2022-11-15 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepage', '0023_auto_20221115_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotentry',
            name='cr_acc0',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_cr0', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='hotentry',
            name='dr_acc0',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_hotentry_dr0', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='material_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='cr_acc0',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_cr0', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='dr_acc0',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_dr0', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='hot_entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_hot_entry', to='primepage.hotentry'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='cr_acc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_cr', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='dr_acc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_dr', to='primepage.account'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='hot_entry',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_hot_entry', to='primepage.hotentry'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partner_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AccPair',
        ),
    ]
