# Generated by Django 3.1.5 on 2022-11-15 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('primepage', '0024_auto_20221115_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentriesbunch_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primepage_moneyentry_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
