# Generated by Django 3.1.5 on 2022-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0027_auto_20221117_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
