# Generated by Django 3.1.5 on 2022-11-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0029_auto_20221117_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='date',
            field=models.DateField(),
        ),
    ]
