# Generated by Django 3.1.5 on 2022-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0031_auto_20221120_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
