# Generated by Django 3.1.5 on 2022-11-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0033_auto_20221120_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyentriesbunch',
            name='has_goodslines',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moneyentry',
            name='has_goodslines',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moneyentriesbunch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moneyentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
