# Generated by Django 3.1.5 on 2022-11-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primepage', '0034_auto_20221120_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyentriesbunch',
            name='has_goodslines',
        ),
        migrations.RemoveField(
            model_name='moneyentry',
            name='has_goodslines',
        ),
    ]
